### ISSUE TITLE
大佬，帮忙看下这个bug

### ISSUE THREAD

**Issue by zlszhonglongshen** [shibing624/nerpy#3]
Traceback (most recent call last):
  File "training_ner_model_file_demo.py", line 15, in <module>
    from nerpy.ner_model import NERModel
  File "../nerpy/__init__.py", line 10, in <module>
    from nerpy.ner_model import NERModel
  File "../nerpy/ner_model.py", line 1675
    return loss, *outputs[1:]
                 ^
SyntaxError: invalid syntax

**Comment by zlszhonglongshen** [comment]
Running Evaluation:   0%|                                                                                                                          | 0/58 [00:02<?, ?it/s]
Epoch 1 of 4:   0%|                                                                                                                                 | 0/4 [16:38<?, ?it/s]
Traceback (most recent call last):
  File "training_ner_model_file_demo.py", line 101, in <module>
    main()
  File "training_ner_model_file_demo.py", line 62, in main
    model.train_model(train_data, eval_data=eval_data)
  File "../nerpy/ner_model.py", line 420, in train_model
    **kwargs,
  File "../nerpy/ner_model.py", line 879, in train
    **kwargs,
  File "../nerpy/ner_model.py", line 1050, in eval_model
    **kwargs,
  File "../nerpy/ner_model.py", line 1115, in evaluate
    preds = logits.detach().cpu().numpy()
AttributeError: 'tuple' object has no attribute 'detach'

**Comment by shibing624** [comment]
要求python3.8 +

**Comment by zlszhonglongshen** [comment]
> 要求python3.8 +

可以了，谢谢大佬。

**Comment by zlszhonglongshen** [comment]
已解决
